import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Nav from "../components/Nav"
import { Footer } from "@/components/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "TicketHub",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      
        <body
          className={`${inter.className} min-h-screen bg-gradient-to-br from-sky-100 to-sky-200`}
        >
          <Nav/>
          <main className="w-full">{children}</main>
          <Footer/>
        </body>
    </html>
  )
}
